"use strict";

const { createHash } = require("node:crypto");
const { validateEmbedding, fingerprintEmbedding } = require("../clustering/ClusterMath");

const VECTOR_INDEX_SCHEMA_VERSION = 1;
const VECTOR_KINDS = Object.freeze({ MEMORY_FRAGMENT: "memory_fragment", SUPER_MEMORY: "super_memory", CLUSTER_CENTROID: "cluster_centroid" });
const KINDS = new Set(Object.values(VECTOR_KINDS));
const HEX = /^[a-f0-9]{64}$/;
const UUID = /^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
const POINT_KEYS = ["schemaVersion","pointId","deduplicationKey","dimension","vector","payload"];
const PAYLOAD_KEYS = ["schema_version","user_id_hash","entity_id","vector_kind","memory_kind","storage_tier","processing_state","consolidated","cluster_id","created_at","source_memory_ids","embedding_model","embedding_version","content_hash","vector_fingerprint"];

class VectorIndexRecordError extends Error { constructor(code,message){super(message);this.name="VectorIndexRecordError";this.code=code;} }
function fail(c,m){throw new VectorIndexRecordError(c,m);}
function plain(v){return v&&typeof v==="object"&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v));}
function clone(v){if(Array.isArray(v))return v.map(clone);if(plain(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v;}
function freeze(v){Object.freeze(v);for(const x of Object.values(v))if(x&&typeof x==="object"&&!Object.isFrozen(x))freeze(x);return v;}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(",")}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;}
function sha(v){return createHash("sha256").update(typeof v==="string"?v:stable(v),"utf8").digest("hex");}
function userHash(userId){if(typeof userId!=="string"||!userId.trim())fail("INVALID_USER","userId must be explicit");return sha(userId.trim());}
function computeVectorFingerprint(vector){try{return fingerprintEmbedding(vector);}catch{fail("INVALID_VECTOR","Vector must be finite, non-empty and non-zero");}}
function dedupPayload(input){const hash=input.userIdHash||userHash(input.userId);return{user_id_hash:hash,entity_id:input.entityId,vector_kind:input.vectorKind,content_hash:input.contentHash,embedding_model:input.embeddingModel,embedding_version:input.embeddingVersion,cluster_id:input.vectorKind==="cluster_centroid"?input.clusterId:null,centroid_fingerprint:input.vectorKind==="cluster_centroid"?input.vectorFingerprint:null};}
function computeVectorDeduplicationKey(input){return sha(dedupPayload(input));}
function uuidFromHash(hash){const bytes=Buffer.from(hash.slice(0,32),"hex");bytes[6]=(bytes[6]&0x0f)|0x50;bytes[8]=(bytes[8]&0x3f)|0x80;const h=bytes.toString("hex");return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20,32)}`;}
function computeVectorPointId(input){return uuidFromHash(computeVectorDeduplicationKey(input));}
function validateKind(payload){const ids=payload.source_memory_ids;if(!KINDS.has(payload.vector_kind))fail("INVALID_KIND","vector_kind is invalid");if(payload.vector_kind==="memory_fragment"){if(!payload.memory_kind||!payload.storage_tier||payload.content_hash===null)fail("INVALID_KIND_FIELDS","memory_fragment fields are incomplete");}else if(payload.vector_kind==="super_memory"){if(payload.memory_kind!=="super_memory"||payload.storage_tier!=="core"||payload.consolidated!==true||ids.length===0||payload.content_hash===null)fail("INVALID_KIND_FIELDS","super_memory fields are invalid");}else{if(!payload.cluster_id||payload.entity_id!==payload.cluster_id||ids.length===0||payload.content_hash!==payload.vector_fingerprint||payload.memory_kind!==null||payload.storage_tier!==null||payload.processing_state!==null||payload.consolidated!==null)fail("INVALID_KIND_FIELDS","cluster_centroid fields are invalid");}}
function validateVectorIndexPoint(point){if(!plain(point)||Object.keys(point).sort().join(",")!==[...POINT_KEYS].sort().join(","))fail("INVALID_POINT","Point schema is closed");const p=clone(point);if(p.schemaVersion!==1||!UUID.test(p.pointId||"")||!HEX.test(p.deduplicationKey||"")||!Number.isInteger(p.dimension)||p.dimension<=0)fail("INVALID_POINT","Point identity is invalid");try{validateEmbedding(p.vector);}catch{fail("INVALID_VECTOR","Vector is invalid");}if(p.vector.length!==p.dimension)fail("DIMENSION_MISMATCH","Vector dimension mismatch");if(!plain(p.payload)||Object.keys(p.payload).sort().join(",")!==[...PAYLOAD_KEYS].sort().join(","))fail("INVALID_PAYLOAD","Payload schema is closed");const q=p.payload;if(q.schema_version!==1||!HEX.test(q.user_id_hash||"")||typeof q.entity_id!=="string"||!q.entity_id||!HEX.test(q.content_hash||"")||!HEX.test(q.vector_fingerprint||"")||computeVectorFingerprint(p.vector)!==q.vector_fingerprint||!Number.isSafeInteger(q.created_at)||q.created_at<0||typeof q.embedding_model!=="string"||!q.embedding_model||typeof q.embedding_version!=="string"||!q.embedding_version||!Array.isArray(q.source_memory_ids)||q.source_memory_ids.some(id=>typeof id!=="string"||!id)||new Set(q.source_memory_ids).size!==q.source_memory_ids.length||stable(q.source_memory_ids)!==stable([...q.source_memory_ids].sort())||![true,false,null].includes(q.consolidated))fail("INVALID_PAYLOAD","Payload values are invalid");validateKind(q);const identity={userIdHash:q.user_id_hash,entityId:q.entity_id,vectorKind:q.vector_kind,contentHash:q.content_hash,embeddingModel:q.embedding_model,embeddingVersion:q.embedding_version,clusterId:q.cluster_id,vectorFingerprint:q.vector_fingerprint};if(computeVectorDeduplicationKey(identity)!==p.deduplicationKey||computeVectorPointId(identity)!==p.pointId)fail("IDENTITY_MISMATCH","Point identity cannot be verified");return freeze(p);}
function createVectorIndexPoint(input){const expected=["userId","entityId","vectorKind","vector","dimension","memoryKind","storageTier","processingState","consolidated","clusterId","createdAt","sourceMemoryIds","embeddingModel","embeddingVersion","contentHash"];if(!plain(input)||Object.keys(input).sort().join(",")!==expected.sort().join(","))fail("INVALID_INPUT","All vector point fields must be explicit");const fingerprint=computeVectorFingerprint(input.vector);const payload={schema_version:1,user_id_hash:userHash(input.userId),entity_id:input.entityId,vector_kind:input.vectorKind,memory_kind:input.memoryKind,storage_tier:input.storageTier,processing_state:input.processingState,consolidated:input.consolidated,cluster_id:input.clusterId,created_at:input.createdAt,source_memory_ids:Array.isArray(input.sourceMemoryIds)?[...input.sourceMemoryIds].sort():input.sourceMemoryIds,embedding_model:input.embeddingModel,embedding_version:input.embeddingVersion,content_hash:input.contentHash,vector_fingerprint:fingerprint};const identity={userIdHash:payload.user_id_hash,entityId:input.entityId,vectorKind:input.vectorKind,contentHash:input.contentHash,embeddingModel:input.embeddingModel,embeddingVersion:input.embeddingVersion,clusterId:input.clusterId,vectorFingerprint:fingerprint};const key=computeVectorDeduplicationKey(identity);return validateVectorIndexPoint({schemaVersion:1,pointId:uuidFromHash(key),deduplicationKey:key,dimension:input.dimension,vector:[...input.vector],payload});}
module.exports={VECTOR_INDEX_SCHEMA_VERSION,VECTOR_KINDS,VectorIndexRecordError,createVectorIndexPoint,validateVectorIndexPoint,computeVectorDeduplicationKey,computeVectorPointId,computeVectorFingerprint};
