"use strict";

const { createHash } = require("node:crypto");
const { validateEmbedding } = require("../clustering/ClusterMath");
const { validateVectorIndexPoint } = require("./VectorIndexRecord");

const VECTOR_PROVIDER_SCHEMA_VERSION=1;
const VECTOR_DISTANCE_METRICS=Object.freeze({COSINE:"Cosine",DOT:"Dot",EUCLID:"Euclid"});
const VECTOR_FILTER_FIELDS=Object.freeze(["user_id_hash","vector_kind","memory_kind","storage_tier","processing_state","consolidated","cluster_id","created_at"]);
const DEFAULT_VECTOR_INDEX_OPTIONS=Object.freeze({timeoutMs:10000});
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/;
const PAYLOAD_FIELDS=new Set(["schema_version","user_id_hash","entity_id","vector_kind","memory_kind","storage_tier","processing_state","consolidated","cluster_id","created_at","source_memory_ids","embedding_model","embedding_version","content_hash","vector_fingerprint"]);
class VectorIndexAdapterError extends Error{constructor(code,phase,message,details={}){super(message);this.name="VectorIndexAdapterError";this.code=code;this.phase=phase;Object.assign(this,details);}}
function fail(c,p,m,d){throw new VectorIndexAdapterError(c,p,m,d);}
function plain(v){return v&&typeof v==="object"&&!Array.isArray(v)&&[Object.prototype,null].includes(Object.getPrototypeOf(v));}
function clone(v){if(Array.isArray(v))return v.map(clone);if(plain(v))return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,clone(x)]));return v;}
function freeze(v){Object.freeze(v);for(const x of Object.values(v))if(x&&typeof x==="object"&&!Object.isFrozen(x))freeze(x);return v;}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(stable).join(",")}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${stable(v[k])}`).join(",")}}`;}
function hashUser(id){if(typeof id!=="string"||!id.trim())fail("INVALID_SEARCH","search","userId is required");return createHash("sha256").update(id.trim()).digest("hex");}
function validateProvider(provider){const methods=["getCollectionInfo","retrieve","upsert","search","delete"];if(!plain(provider)||provider.schemaVersion!==1||typeof provider.id!=="string"||!provider.id||methods.some(m=>typeof provider[m]!=="function"))fail("INVALID_PROVIDER","configuration","Provider must implement vector V1");}
async function timed(provider,method,args,timeoutMs,phase){const controller=new AbortController();let timer;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(new VectorIndexAdapterError("PROVIDER_TIMEOUT",phase,"Vector provider timed out"));},timeoutMs);});try{return await Promise.race([Promise.resolve().then(()=>provider[method]({...args,signal:controller.signal})).catch(()=>fail("PROVIDER_FAILURE",phase,"Vector provider call failed",{providerId:provider.id})),timeout]);}finally{clearTimeout(timer);}}
function createVectorIndexAdapter(options={}){if(!plain(options)||Object.keys(options).some(k=>!["provider","collection","dimension","distance","timeoutMs"].includes(k)))fail("INVALID_OPTIONS","configuration","Adapter options are invalid");validateProvider(options.provider);if(typeof options.collection!=="string"||!options.collection.trim()||!Number.isInteger(options.dimension)||options.dimension<=0||!Object.values(VECTOR_DISTANCE_METRICS).includes(options.distance))fail("INVALID_OPTIONS","configuration","Collection, dimension and distance are explicit");const timeoutMs=options.timeoutMs===undefined?DEFAULT_VECTOR_INDEX_OPTIONS.timeoutMs:options.timeoutMs;if(!Number.isInteger(timeoutMs)||timeoutMs<=0)fail("INVALID_OPTIONS","configuration","timeoutMs must be positive");const provider=options.provider,collection=options.collection;
  async function collectionInfo(){const info=await timed(provider,"getCollectionInfo",{collection},timeoutMs,"collection");if(!plain(info)||typeof info.exists!=="boolean")fail("INVALID_COLLECTION_RESPONSE","collection","Collection response is invalid");if(!info.exists)fail("COLLECTION_NOT_FOUND","collection","Vector collection does not exist");if(info.dimension!==options.dimension)fail("COLLECTION_DIMENSION_MISMATCH","collection","Vector collection dimension mismatch");if(info.distance!==options.distance)fail("COLLECTION_DISTANCE_MISMATCH","collection","Vector collection distance mismatch");return info;}
  function validPoint(point){const p=validateVectorIndexPoint(point);if(p.dimension!==options.dimension)fail("POINT_DIMENSION_MISMATCH","validation","Point dimension does not match adapter");return p;}
  function responseOk(r,phase){if(!plain(r)||r.ok!==true||!Number.isInteger(r.status)||r.status<200||r.status>299)fail("PROVIDER_RESPONSE_FAILED",phase,"Vector provider response was unsuccessful",{providerStatus:Number.isInteger(r?.status)?r.status:null});}
  async function upsertMany(points){if(!Array.isArray(points)||!points.length)fail("INVALID_POINTS","validation","Points must be non-empty");const validated=points.map(validPoint).sort((a,b)=>a.pointId.localeCompare(b.pointId));if(new Set(validated.map(p=>p.pointId)).size!==validated.length)fail("DUPLICATE_POINT_ID","validation","Batch point IDs must be unique");await collectionInfo();const existing=await timed(provider,"retrieve",{collection,pointIds:validated.map(p=>p.pointId)},timeoutMs,"retrieve");if(!Array.isArray(existing))fail("INVALID_PROVIDER_RESULT","retrieve","Retrieve result must be an array");const byId=new Map(existing.map(p=>[p.pointId||p.id,p]));const fresh=[],replayed=[];for(const point of validated){const old=byId.get(point.pointId);if(!old){fresh.push(point);continue;}let checked;try{checked=validateVectorIndexPoint(old);}catch{fail("POINT_CONFLICT","upsert","Existing point is incompatible",{pointId:point.pointId});}if(checked.deduplicationKey!==point.deduplicationKey||checked.payload.vector_fingerprint!==point.payload.vector_fingerprint||stable(checked.payload)!==stable(point.payload))fail("POINT_CONFLICT","upsert","Existing point has conflicting semantics",{pointId:point.pointId});replayed.push(point.pointId);}if(fresh.length){const response=await timed(provider,"upsert",{collection,points:fresh.map(clone)},timeoutMs,"upsert");responseOk(response,"upsert");}return freeze({createdCount:fresh.length,replayedCount:replayed.length,conflictedCount:0,createdPointIds:fresh.map(p=>p.pointId),replayedPointIds:replayed});}
  async function upsert(point){const p=validPoint(point);const report=await upsertMany([p]);return freeze({pointId:p.pointId,created:report.createdCount===1,idempotentReplay:report.replayedCount===1});}
  function list(value,label,allowed){if(value===undefined)return null;if(!Array.isArray(value)||!value.length||value.some(x=>typeof x!=="string"||!x)||new Set(value).size!==value.length)fail("INVALID_SEARCH","search",`${label} is invalid`);if(allowed&&value.some(x=>!allowed.includes(x)))fail("INVALID_SEARCH","search",`${label} contains unknown values`);return[...value].sort();}
  async function search(request={}){const allowed=new Set(["vector","userId","limit","vectorKinds","memoryKinds","storageTiers","processingStates","consolidated","clusterIds","createdAtFrom","createdAtTo"]);if(!plain(request)||Object.keys(request).some(k=>!allowed.has(k)))fail("INVALID_SEARCH","search","Search request has unknown fields");try{validateEmbedding(request.vector);}catch{fail("INVALID_SEARCH_VECTOR","search","Search vector is invalid");}if(request.vector.length!==options.dimension||!Number.isInteger(request.limit)||request.limit<=0)fail("INVALID_SEARCH","search","Dimension and positive limit are required");if(request.consolidated!==undefined&&typeof request.consolidated!=="boolean"||request.createdAtFrom!==undefined&&!Number.isSafeInteger(request.createdAtFrom)||request.createdAtTo!==undefined&&!Number.isSafeInteger(request.createdAtTo)||request.createdAtFrom!==undefined&&request.createdAtTo!==undefined&&request.createdAtFrom>request.createdAtTo)fail("INVALID_SEARCH","search","Search range or flags are invalid");const filters={user_id_hash:hashUser(request.userId),vector_kind:list(request.vectorKinds,"vectorKinds",["memory_fragment","super_memory","cluster_centroid"]),memory_kind:list(request.memoryKinds,"memoryKinds"),storage_tier:list(request.storageTiers,"storageTiers",["core","warm","deep"]),processing_state:list(request.processingStates,"processingStates"),consolidated:request.consolidated??null,cluster_id:list(request.clusterIds,"clusterIds"),created_at:{from:request.createdAtFrom??null,to:request.createdAtTo??null}};await collectionInfo();const results=await timed(provider,"search",{collection,vector:[...request.vector],filter:filters,limit:request.limit},timeoutMs,"search");if(!Array.isArray(results))fail("INVALID_PROVIDER_RESULT","search","Search result must be an array");return freeze(results.map(item=>{if(!plain(item)||!UUID.test(item.pointId||item.id||"")||typeof item.score!=="number"||!Number.isFinite(item.score)||!plain(item.payload)||Object.keys(item.payload).some(key=>!PAYLOAD_FIELDS.has(key))||Object.keys(item.payload).length!==PAYLOAD_FIELDS.size)fail("INVALID_PROVIDER_RESULT","search","Search item is invalid");return{pointId:item.pointId||item.id,rawScore:item.score,payload:clone(item.payload)};}));}
  async function remove(pointIds){if(!Array.isArray(pointIds)||!pointIds.length||pointIds.some(id=>!UUID.test(id))||new Set(pointIds).size!==pointIds.length)fail("INVALID_POINT_IDS","delete","Explicit unique point IDs are required");const response=await timed(provider,"delete",{collection,pointIds:[...pointIds].sort()},timeoutMs,"delete");responseOk(response,"delete");return freeze({deletedCount:pointIds.length,pointIds:[...pointIds].sort()});}
  async function inspect(pointIds){if(!Array.isArray(pointIds)||pointIds.some(id=>!UUID.test(id)))fail("INVALID_POINT_IDS","inspect","Point IDs are invalid");const result=await timed(provider,"retrieve",{collection,pointIds:[...pointIds].sort()},timeoutMs,"inspect");if(!Array.isArray(result))fail("INVALID_PROVIDER_RESULT","inspect","Retrieve result must be an array");return freeze({requestedCount:pointIds.length,foundPointIds:result.map(p=>p.pointId||p.id).sort()});}
  async function healthCheck(){const info=await collectionInfo();return freeze({ok:true,providerId:provider.id,collection,dimension:info.dimension,distance:info.distance});}
  return Object.freeze({upsert,upsertMany,search,delete:remove,inspect,healthCheck});}
module.exports={VECTOR_PROVIDER_SCHEMA_VERSION,VECTOR_DISTANCE_METRICS,VECTOR_FILTER_FIELDS,DEFAULT_VECTOR_INDEX_OPTIONS,VectorIndexAdapterError,createVectorIndexAdapter};
