"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const os=require("node:os");const path=require("node:path");const {createHash}=require("node:crypto");
const JsonMemoryStorage=require("../../core/JsonMemoryStorage");const {createFileLockManager}=require("../../core/locking/FileLockManager");const {createProcessingState}=require("../../core/consolidation/ProcessingState");const {createHippocampusJournal}=require("../../core/hippocampus/HippocampusJournal");const {createRecoveryManager,RECOVERY_ACTIONS}=require("../../core/hippocampus/RecoveryManager");const {createSourceClaimPlan,createJournalSourceClaimDescriptor,claimSources}=require("../../core/hippocampus/SourceClaimTransaction");
const USER="recovery-user",BASE=1900000000000;const sha=x=>createHash("sha256").update(x).digest("hex");function temp(t){const d=fs.mkdtempSync(path.join(os.tmpdir(),"fix14-"));t.after(()=>fs.rmSync(d,{recursive:true,force:true}));return d;}function clock(start=BASE){let n=start;return()=>n++;}function raw(id){return{id,type:"episodic",content:{text:`source ${id}`,keep:true},timestamp:BASE-100,memoryKind:"raw",storageTier:"warm",unknown:{keep:true},processing:createProcessingState({state:"raw",revision:0,attempt_id:null,updated_at:BASE-200,error:null})};}function event(type,run="run-1",extra={}){return{event_type:type,run_id:run,mode:"commit",phase:"commit",status:"ok",timestamp:BASE,...extra};}

test("journal append sequences, fingerprints and idempotent replay",async t=>{const d=temp(t),j=createHippocampusJournal({directory:d,userId:USER,clock:clock()});const a=await j.append(event("RUN_STARTED"));const b=await j.append(event("PLAN_COMPLETED", "run-1",{timestamp:BASE+1}));assert.equal(a.event.sequence,1);assert.equal(b.event.sequence,2);assert.match(a.event.event_id,/^[a-f0-9]{64}$/);assert.match(a.event.event_fingerprint,/^[a-f0-9]{64}$/);assert.equal((await j.append(event("RUN_STARTED"))).idempotentReplay,true);assert.equal((await j.readAll()).length,2);assert.doesNotMatch(j.fileName,/recovery-user/);});
test("journal rejects private fields",async t=>{const j=createHippocampusJournal({directory:temp(t),userId:USER});await assert.rejects(j.append(event("RUN_STARTED","r",{details:{prompt:"private"}})),{code:"PRIVATE_EVENT_FIELD"});});
test("journal detects and repairs only truncated tail with backup",async t=>{const d=temp(t),j=createHippocampusJournal({directory:d,userId:USER});await j.append(event("RUN_STARTED"));const file=path.join(d,j.fileName);fs.appendFileSync(file,'{"broken"');const inspection=await j.inspect();assert.equal(inspection.tailIncomplete,true);assert.equal((await j.repairTail({})).dryRun,true);await assert.rejects(j.repairTail({commitRepair:true}),{code:"REPAIR_CONFIRMATION_REQUIRED"});const report=await j.repairTail({commitRepair:true,confirmRepair:"REPAIR_HIPPOCAMPUS_JOURNAL_V1"});assert.equal(report.repaired,true);assert.equal(fs.existsSync(`${file}.bak`),true);assert.equal((await j.readAll()).length,1);});
test("journal blocks intermediate corruption and altered fingerprint/sequence",async t=>{const d=temp(t),j=createHippocampusJournal({directory:d,userId:USER});await j.append(event("RUN_STARTED"));await j.append(event("PLAN_COMPLETED","run-1",{timestamp:BASE+1}));const file=path.join(d,j.fileName);const lines=fs.readFileSync(file,"utf8").trim().split("\n");fs.writeFileSync(file,`${lines[0]}\nnot-json\n${lines[1]}\n`);assert.equal((await j.inspect()).corruption,"JOURNAL_CORRUPT_INTERMEDIATE");await assert.rejects(j.repairTail({commitRepair:true,confirmRepair:"REPAIR_HIPPOCAMPUS_JOURNAL_V1"}),{code:"REPAIR_BLOCKED"});});
test("incomplete run classifications cover claim, synthesis, commit and orphan",async t=>{const j=createHippocampusJournal({directory:temp(t),userId:USER});for(const [run,types]of [["claim",["RUN_STARTED","SOURCES_CLAIMED"]],["synth",["RUN_STARTED","SYNTHESIS_STARTED"]],["success",["RUN_STARTED","SYNTHESIS_SUCCEEDED"]],["commit",["RUN_STARTED","COMMIT_STARTED"]],["done",["RUN_STARTED","COMMIT_SUCCEEDED"]],["orphan",["RUN_STARTED","CLUSTER_PERSISTED"]]])for(let i=0;i<types.length;i++)await j.append(event(types[i],run,{timestamp:BASE+i,cluster_id:`c-${run}`}));const map=Object.fromEntries((await j.findIncompleteRuns()).map(x=>[x.runId,x.classification]));assert.deepEqual(map,{claim:"CORRUPT_OR_AMBIGUOUS",commit:"COMMIT_STARTED_NO_RESULT",done:"COMMIT_SUCCEEDED_NO_RUN_COMPLETION",orphan:"CLUSTER_PERSISTED_NO_CLAIM",success:"SYNTHESIS_SUCCEEDED_NO_COMMIT",synth:"SYNTHESIS_STARTED_NO_RESULT"});});
test("journal lock serializes concurrent append",async t=>{const j=createHippocampusJournal({directory:temp(t),userId:USER});await Promise.all(Array.from({length:12},(_,i)=>j.append(event("RECOVERY_ACTION",`r-${i}`,{timestamp:BASE+i,details:{index:i}}))));assert.deepEqual((await j.readAll()).map(x=>x.sequence),Array.from({length:12},(_,i)=>i+1));});

test("lock inspection never removes recent or live PID lock",async t=>{const d=temp(t),m=createFileLockManager({lockDirectory:d});const h=await m.acquire("key");const state=await m.inspect("key",{staleAfterMs:1});assert.equal(state.exists,true);assert.equal(state.pidAlive,true);assert.equal(state.staleCandidate,false);await assert.rejects(m.recoverStale("key",{staleAfterMs:1,recover:true,confirmRecovery:"RECOVER_STALE_LOCK_V1"}),{code:"LOCK_RECOVERY_BLOCKED"});await m.release(h);});
test("dead local old lock requires confirmation and recovers idempotently",async t=>{const d=temp(t),m=createFileLockManager({lockDirectory:d});fs.mkdirSync(d,{recursive:true});const key="dead",file=path.join(d,`${sha(key)}.lock`);fs.writeFileSync(file,JSON.stringify({schemaVersion:1,token:"t",ownerId:"o",pid:99999999,host:os.hostname(),createdAt:0}));assert.equal((await m.inspect(key,{staleAfterMs:1})).staleCandidate,true);await assert.rejects(m.recoverStale(key,{staleAfterMs:1,recover:true}),{code:"LOCK_RECOVERY_CONFIRMATION_REQUIRED"});assert.equal((await m.recoverStale(key,{staleAfterMs:1,recover:true,confirmRecovery:"RECOVER_STALE_LOCK_V1"})).recovered,true);assert.equal((await m.recoverStale(key,{staleAfterMs:1,recover:true,confirmRecovery:"RECOVER_STALE_LOCK_V1"})).idempotentReplay,true);});
test("foreign host stale lock is blocked",async t=>{const d=temp(t),m=createFileLockManager({lockDirectory:d});const key="foreign";fs.writeFileSync(path.join(d,`${sha(key)}.lock`),JSON.stringify({schemaVersion:1,token:"t",ownerId:"o",pid:99999999,host:"another-host",createdAt:0}));await assert.rejects(m.recoverStale(key,{staleAfterMs:1,recover:true,confirmRecovery:"RECOVER_STALE_LOCK_V1"}),{code:"LOCK_RECOVERY_BLOCKED"});});
test("JsonMemoryStorage delegates user lock inspection/recovery",async t=>{const d=temp(t),s=new JsonMemoryStorage(d);assert.equal((await s.inspectUserLock(USER,{staleAfterMs:1})).exists,false);});

async function claimedFixture(t){const d=temp(t),s=new JsonMemoryStorage(d),mem=[raw("a"),raw("b")];await s.saveMemories(USER,mem);const hashes=Object.fromEntries(mem.map(m=>[m.id,sha(m.content.text)]));const plan=createSourceClaimPlan({userId:USER,sourceMemories:mem,sourceIds:["a","b"],attemptId:"attempt-1",claimedAt:BASE,sourceContentHashes:hashes});await claimSources({storage:s,plan});const c=clock(BASE+1000),j=createHippocampusJournal({directory:d,userId:USER,clock:c});await j.append(event("RUN_STARTED","interrupted",{timestamp:BASE-1000}));await j.append(event("SOURCES_CLAIMED","interrupted",{timestamp:BASE-999,cluster_id:"cluster-1",attempt_id:"attempt-1",source_memory_ids:["a","b"],details:{claimPlan:createJournalSourceClaimDescriptor(plan)}}));const r=createRecoveryManager({storage:s,journal:j,userId:USER,clock:c,recoveryGraceMs:10});return{d,s,j,r,plan};}
test("recovery plan is deterministic and dry-run",async t=>{const x=await claimedFixture(t);const a=await x.r.buildRecoveryPlan({generatedAt:BASE+1000}),b=await x.r.buildRecoveryPlan({generatedAt:BASE+1000});assert.deepEqual(a,b);assert.equal(a.dryRun,true);assert.equal(a.actions[0].action,RECOVERY_ACTIONS.MARK_INTERRUPTED_CLAIM_FAILED);for(const id of["a","b"])assert.equal((await x.s.getMemory(USER,id)).processing.state,"synthesizing");});
test("recovery requires confirmation, marks interrupted claim failed once",async t=>{const x=await claimedFixture(t),plan=await x.r.buildRecoveryPlan({generatedAt:BASE+1000});await assert.rejects(x.r.executeRecovery({plan}),{code:"RECOVERY_CONFIRMATION_REQUIRED"});const done=await x.r.executeRecovery({plan,execute:true,confirmRecovery:"RECOVER_HIPPOCAMPUS_V1"});assert.equal(done.executed,2);const revisions=[];for(const id of["a","b"]){const m=await x.s.getMemory(USER,id);assert.equal(m.processing.state,"failed");assert.equal(m.processing.error.code,"RECOVERY_INTERRUPTED_ATTEMPT");revisions.push(m.processing.revision);}const next=await x.r.buildRecoveryPlan({generatedAt:BASE+2000});assert.equal(next.actions.length,0);assert.deepEqual([ (await x.s.getMemory(USER,"a")).processing.revision,(await x.s.getMemory(USER,"b")).processing.revision],revisions);});
test("grace period blocks recent claimed run",async t=>{const x=await claimedFixture(t);const plan=await x.r.buildRecoveryPlan({generatedAt:BASE-995});assert.equal(plan.actions.length,0);assert.equal(plan.blockedItems[0].reasonCode,"GRACE_PERIOD_ACTIVE");});
test("unattributed synthesizing is blocked",async t=>{const d=temp(t),s=new JsonMemoryStorage(d),m=raw("x");m.processing=createProcessingState({state:"synthesizing",revision:2,attempt_id:"unknown",updated_at:BASE,error:null});await s.saveMemories(USER,[m]);const j=createHippocampusJournal({directory:d,userId:USER}),r=createRecoveryManager({storage:s,journal:j,userId:USER,clock:clock(),recoveryGraceMs:1});const plan=await r.buildRecoveryPlan({generatedAt:BASE+100});assert.equal(plan.blockedItems.some(x=>x.action===RECOVERY_ACTIONS.BLOCK_UNATTRIBUTED_SYNTHESIZING),true);});
test("recovery fingerprint preconditions reject changed memory",async t=>{const x=await claimedFixture(t),plan=await x.r.buildRecoveryPlan({generatedAt:BASE+1000});const all=await x.s.loadMemories(USER);all[0].unknown.changed=true;await x.s.saveMemories(USER,all);await assert.rejects(x.r.executeRecovery({plan,execute:true,confirmRecovery:"RECOVER_HIPPOCAMPUS_V1"}),{code:"STALE_RECOVERY_PLAN"});});
test("orphan cluster is journal-only reconciliation",async t=>{const d=temp(t),s=new JsonMemoryStorage(d);await s.saveMemories(USER,[]);const c=clock(BASE+100),j=createHippocampusJournal({directory:d,userId:USER,clock:c});await j.append(event("RUN_STARTED","orphan",{timestamp:BASE}));await j.append(event("CLUSTER_PERSISTED","orphan",{timestamp:BASE+1,cluster_id:"cluster"}));const r=createRecoveryManager({storage:s,journal:j,userId:USER,clock:c,recoveryGraceMs:1}),plan=await r.buildRecoveryPlan({generatedAt:BASE+100});assert.equal(plan.actions[0].action,RECOVERY_ACTIONS.RECORD_ORPHAN_CLUSTER);await r.executeRecovery({plan,execute:true,confirmRecovery:"RECOVER_HIPPOCAMPUS_V1"});assert.equal((await j.findIncompleteRuns()).length,0);assert.equal((await s.loadMemories(USER)).length,0);});
test("recovery reports contain no private memory content",async t=>{const x=await claimedFixture(t),plan=await x.r.buildRecoveryPlan({generatedAt:BASE+1000});assert.doesNotMatch(JSON.stringify(plan),/source a|source b|prompt|raw_output|centroid/);});
