"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const {createHash}=require("node:crypto");
const {VECTOR_KINDS,createVectorIndexPoint,validateVectorIndexPoint,computeVectorDeduplicationKey,computeVectorPointId,computeVectorFingerprint}=require("../../core/vector/VectorIndexRecord");
const {VECTOR_DISTANCE_METRICS,VECTOR_FILTER_FIELDS,createVectorIndexAdapter}=require("../../core/vector/VectorIndexAdapter");
const HASH=createHash("sha256").update("content").digest("hex");
function input(over={}){return{userId:"synthetic-user",entityId:"mem-1",vectorKind:"memory_fragment",vector:[1,0],dimension:2,memoryKind:"episodic",storageTier:"warm",processingState:"raw",consolidated:false,clusterId:null,createdAt:1800000000000,sourceMemoryIds:[],embeddingModel:"embed-model",embeddingVersion:"v1",contentHash:HASH,...over};}
function point(over={}){return createVectorIndexPoint(input(over));}
function provider(over={}){const points=new Map(),calls=[];return{schemaVersion:1,id:"synthetic-provider",calls,points,async getCollectionInfo(args){calls.push(["info",args]);return{exists:true,dimension:2,distance:"Cosine"};},async retrieve(args){calls.push(["retrieve",args]);return args.pointIds.map(id=>points.get(id)).filter(Boolean);},async upsert(args){calls.push(["upsert",args]);for(const p of args.points)points.set(p.pointId,p);return{ok:true,status:200};},async search(args){calls.push(["search",args]);return[...points.values()].slice(0,args.limit).map(p=>({pointId:p.pointId,score:-0.25,payload:p.payload}));},async delete(args){calls.push(["delete",args]);for(const id of args.pointIds)points.delete(id);return{ok:true,status:200};},...over};}
function adapter(p=provider(),over={}){return{p,a:createVectorIndexAdapter({provider:p,collection:"synthetic-collection",dimension:2,distance:"Cosine",timeoutMs:100,...over})};}

test("creates all three strict vector kinds",()=>{const fragment=point();const sm=point({entityId:"sm-1",vectorKind:"super_memory",memoryKind:"super_memory",storageTier:"core",processingState:"consolidated",consolidated:true,sourceMemoryIds:["a","b"]});const cluster=point({entityId:"cluster-1",vectorKind:"cluster_centroid",memoryKind:null,storageTier:null,processingState:null,consolidated:null,clusterId:"cluster-1",sourceMemoryIds:["a","b"],contentHash:computeVectorFingerprint([1,0])});assert.equal(fragment.payload.vector_kind,VECTOR_KINDS.MEMORY_FRAGMENT);assert.equal(sm.payload.vector_kind,VECTOR_KINDS.SUPER_MEMORY);assert.equal(cluster.payload.vector_kind,VECTOR_KINDS.CLUSTER_CENTROID);});
test("user hash, dedup key and UUID are deterministic",()=>{const a=point(),b=point();assert.deepEqual(a,b);assert.equal(a.payload.user_id_hash,createHash("sha256").update("synthetic-user").digest("hex"));assert.match(a.pointId,/^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);assert.equal(computeVectorPointId({userIdHash:a.payload.user_id_hash,entityId:a.payload.entity_id,vectorKind:a.payload.vector_kind,contentHash:a.payload.content_hash,embeddingModel:a.payload.embedding_model,embeddingVersion:a.payload.embedding_version,clusterId:null,vectorFingerprint:a.payload.vector_fingerprint}),a.pointId);assert.match(computeVectorDeduplicationKey(input()),/^[a-f0-9]{64}$/);});
test("logical identity changes point ID",()=>{const base=point().pointId;for(const changed of[{contentHash:"a".repeat(64)},{embeddingModel:"other"},{embeddingVersion:"v2"},{vectorKind:"super_memory",memoryKind:"super_memory",storageTier:"core",processingState:"consolidated",consolidated:true,sourceMemoryIds:["a"]}])assert.notEqual(point(changed).pointId,base);});
test("vector fingerprint uses canonical JSON numeric serialization",()=>{assert.equal(computeVectorFingerprint([1,0]),createHash("sha256").update(JSON.stringify([1,0])).digest("hex"));assert.notEqual(computeVectorFingerprint([1,0]),computeVectorFingerprint([1,0.1]));});
test("rejects invalid vectors, dimensions, timestamps and source IDs",()=>{for(const over of[{vector:[]},{vector:[0,0]},{vector:[NaN,1]},{dimension:3},{createdAt:-1},{sourceMemoryIds:["a","a"]}])assert.throws(()=>point(over));});
test("enforces kind-specific rules",()=>{assert.throws(()=>point({vectorKind:"super_memory"}));assert.throws(()=>point({vectorKind:"cluster_centroid",memoryKind:null,storageTier:null,processingState:null,consolidated:null,clusterId:"c",entityId:"other",sourceMemoryIds:["a"],contentHash:computeVectorFingerprint([1,0])}));assert.throws(()=>point({vectorKind:"unknown"}));});
test("payload is private, closed, detached and deeply frozen",()=>{const source=input(),p=createVectorIndexPoint(source);assert.doesNotMatch(JSON.stringify(p.payload),/synthetic-user|text|title|facts|prompt|sourceSnapshot/);assert.equal(Object.isFrozen(p),true);assert.equal(Object.isFrozen(p.payload),true);assert.notStrictEqual(p.vector,source.vector);assert.deepEqual(source,input());const tampered=structuredClone(p);tampered.payload.text="private";assert.throws(()=>validateVectorIndexPoint(tampered),{code:"INVALID_PAYLOAD"});});
test("provider, collection, dimension and distance are mandatory",()=>{for(const options of[{}, {provider:{}},{provider:provider(),collection:"",dimension:2,distance:"Cosine"},{provider:provider(),collection:"x",dimension:0,distance:"Cosine"},{provider:provider(),collection:"x",dimension:2,distance:"Unknown"}])assert.throws(()=>createVectorIndexAdapter(options));assert.equal(VECTOR_DISTANCE_METRICS.COSINE,"Cosine");assert.ok(VECTOR_FILTER_FIELDS.includes("user_id_hash"));});
test("collection absence, dimension and distance mismatches fail closed",async()=>{for(const info of[{exists:false,dimension:2,distance:"Cosine"},{exists:true,dimension:3,distance:"Cosine"},{exists:true,dimension:2,distance:"Dot"}]){const p=provider({async getCollectionInfo(){return info;}}),a=adapter(p).a;await assert.rejects(a.upsert(point()));}});
test("upsert creates once then replays without write",async()=>{const {p,a}=adapter();assert.deepEqual(await a.upsert(point()),{pointId:point().pointId,created:true,idempotentReplay:false});assert.deepEqual(await a.upsert(point()),{pointId:point().pointId,created:false,idempotentReplay:true});assert.equal(p.calls.filter(([name])=>name==="upsert").length,1);});
test("existing incompatible point conflicts without overwrite",async()=>{const {p,a}=adapter(),good=point(),bad=structuredClone(good);bad.payload.vector_fingerprint="0".repeat(64);p.points.set(good.pointId,bad);await assert.rejects(a.upsert(good),{code:"POINT_CONFLICT"});assert.equal(p.calls.some(([n])=>n==="upsert"),false);});
test("provider unsuccessful upsert/delete are rejected",async()=>{await assert.rejects(adapter(provider({async upsert(){return{ok:false,status:500};}})).a.upsert(point()),{code:"PROVIDER_RESPONSE_FAILED"});const x=adapter(provider({async delete(){return{ok:false,status:500};}}));await assert.rejects(x.a.delete([point().pointId]),{code:"PROVIDER_RESPONSE_FAILED"});});
test("upsertMany validates all and supports twelve without top five",async()=>{const {p,a}=adapter(),points=Array.from({length:12},(_,i)=>point({entityId:`m-${i}`,contentHash:createHash("sha256").update(`c-${i}`).digest("hex")}));const report=await a.upsertMany(points);assert.equal(report.createdCount,12);assert.equal(p.points.size,12);assert.equal(p.calls.filter(([n])=>n==="upsert").length,1);const bad=[points[0],points[0]];await assert.rejects(a.upsertMany(bad),{code:"DUPLICATE_POINT_ID"});});
test("upsertMany validates complete batch before provider write",async()=>{const {p,a}=adapter();await assert.rejects(a.upsertMany([point(),{bad:true}]));assert.equal(p.calls.some(([n])=>n==="upsert"),false);});
test("search builds only allowlisted deterministic filters and preserves raw score",async()=>{const {p,a}=adapter();await a.upsert(point());const results=await a.search({vector:[1,0],userId:"synthetic-user",limit:12,vectorKinds:["memory_fragment"],memoryKinds:["episodic"],storageTiers:["core","warm","deep"],processingStates:["raw"],consolidated:false,clusterIds:["cluster"],createdAtFrom:1,createdAtTo:2});assert.equal(results[0].rawScore,-0.25);const request=p.calls.find(([n])=>n==="search")[1];assert.equal(request.filter.user_id_hash,point().payload.user_id_hash);assert.deepEqual(request.filter.vector_kind,["memory_fragment"]);assert.deepEqual(request.filter.storage_tier,["core","deep","warm"]);assert.deepEqual(request.filter.created_at,{from:1,to:2});assert.ok(request.signal instanceof AbortSignal);});
test("search rejects arbitrary filters, invalid ranges and missing limit",async()=>{const {a}=adapter();for(const request of[{vector:[1,0],userId:"u",limit:1,filter:{}},{vector:[1,0],userId:"u"},{vector:[1,0],userId:"u",limit:1,createdAtFrom:2,createdAtTo:1},{vector:[1,0],userId:"u",limit:1,storageTiers:["unknown"]}])await assert.rejects(a.search(request));});
test("delete and inspect affect only explicit vector points",async()=>{const {p,a}=adapter();await a.upsert(point());assert.deepEqual(await a.inspect([point().pointId]),{requestedCount:1,foundPointIds:[point().pointId]});assert.equal((await a.delete([point().pointId])).deletedCount,1);assert.equal(p.points.size,0);});
test("cooperative and non-cooperative providers time out with sanitized errors",async()=>{for(const generate of[({signal})=>new Promise((_,reject)=>signal.addEventListener("abort",()=>reject(new Error("private vector 1,0")))),()=>new Promise(()=>{})]){const p=provider({getCollectionInfo:generate}),a=adapter(p,{timeoutMs:10}).a;await assert.rejects(a.healthCheck(),e=>{assert.equal(e.code,"PROVIDER_TIMEOUT");assert.doesNotMatch(e.message,/1,0|payload|vector/);return true;});}});
test("successful calls clear timeout and healthCheck is sanitized",async()=>{const {a}=adapter();assert.deepEqual(await a.healthCheck(),{ok:true,providerId:"synthetic-provider",collection:"synthetic-collection",dimension:2,distance:"Cosine"});await new Promise(resolve=>setTimeout(resolve,15));});
test("modules contain no network, Qdrant client, storage or embedding generation",()=>{const source=["VectorIndexRecord.js","VectorIndexAdapter.js"].map(f=>fs.readFileSync(path.join(__dirname,"../../core/vector",f),"utf8")).join("\n");assert.doesNotMatch(source,/fetch\s*\(|https?:|JsonMemoryStorage|KebloMemory|RecallRouter|HippocampusDaemon|generateEmbedding|QdrantClient/);});
